In [ ]:
from discovery_utils.utils import search
from discovery_utils.getters import gtr

from discovery_utils import PROJECT_DIR
VECTOR_DB_DIR = PROJECT_DIR / 'tmp/vector_db'

GTR = gtr.GtrGetter(vector_db_path=VECTOR_DB_DIR)

In [ ]:
Search = search.SearchDataset(GTR, GTR.projects_enriched, "config.yaml")

In [ ]:
search_df = Search.do_search()

In [87]:
from discovery_utils.utils import (
    analysis,
    analysis_gtr,
)
import importlib
importlib.reload(analysis);
importlib.reload(analysis_gtr);

In [ ]:
df = (
    search_df
    .merge(GTR.get_projects_text(), on='id', how='left')
    .query("_score_avg > 0.3")
)
print(len(df))
df_dedup = analysis_gtr.deduplicate_projects(df, description_column='text')
print(len(df_dedup))

In [ ]:
analysis_gtr.funding_per_period(df, period='year', min_year=2010, max_year=2024)

In [ ]:
ts_df = analysis_gtr.get_timeseries(df, period='year', min_year=2010, max_year=2024)
analysis.magnitude_growth(ts_df, 2019, 2024)
# ts_df

In [ ]:
from discovery_utils.getters import crunchbase
CB = crunchbase.CrunchbaseGetter(vector_db_path=VECTOR_DB_DIR)

In [ ]:
SearchCB = search.SearchDataset(CB, CB.organisations_enriched, "config.yaml")
search_cb_df = SearchCB.do_search()

In [ ]:
orgs_df = CB.organisations_enriched.copy()
funds_df = CB.funding_rounds_enriched.copy()

In [391]:
importlib.reload(crunchbase);
CB = crunchbase.CrunchbaseGetter(vector_db_path=VECTOR_DB_DIR)
CB._organisations_enriched = orgs_df
CB._funding_rounds_enriched = funds_df

2024-11-20 16:59:36,544 - discovery_utils.getters.crunchbase - INFO - Checking for latest version of data in S3 bucket: discovery-iss

2024-11-20 16:59:36,660 - discovery_utils.getters.crunchbase - INFO - Latest Crunchbase version found: Crunchbase_2024-11-18

In [116]:
df = (
    search_cb_df
    .query("_score_avg > 0.3")
)

In [204]:
from discovery_utils.utils import (
    analysis,
    analysis_crunchbase,
)
importlib.reload(analysis);
importlib.reload(analysis_crunchbase);

In [ ]:
analysis_crunchbase.orgs_founded_per_period(df, 'year', 2010, 2024)

In [133]:
matching_ids = df.id.to_list()

In [134]:
selected_funding_df = (
    CB.funding_rounds_enriched
    .query("org_id in @matching_ids")
    .query(f"year >= {2010}")
    .query(f"year <= {2024}")
    # .query(f"investment_type in @include_deals")
    .drop_duplicates("funding_round_id")
)

In [191]:
importlib.reload(analysis_crunchbase);

In [ ]:
analysis_crunchbase

In [ ]:
deals_df, deal_counts_df = analysis_crunchbase.get_funding_by_year_and_range(selected_funding_df, 2014, 2024)
deals_df

In [ ]:
deal_counts_df

In [ ]:
(
    selected_funding_df
    .query("announced_on >= '2015-01-01'")
    .query("announced_on < '2016-01-01'")
    .raised_amount_gbp.sum()
)

In [276]:
importlib.reload(analysis_crunchbase);
ts_df = analysis_crunchbase.get_timeseries(df, selected_funding_df, 'year', 2010, 2024)

In [293]:
ts_df

,time_period,year,n_rounds,raised_amount_usd_total,raised_amount_gbp_total,n_orgs_founded
0,2010-01-01,2010,5,3.073000,1.929978,5
1,2011-01-01,2011,6,5.775000,3.608702,2
2,2012-01-01,2012,5,1.467900,0.925512,4
3,2013-01-01,2013,2,0.015000,0.009968,10
4,2014-01-01,2014,7,2.890469,1.702734,14
5,2015-01-01,2015,6,3.067977,2.020709,5
6,2016-01-01,2016,5,3.912430,2.742130,6
7,2017-01-01,2017,3,0.734822,0.565402,7
8,2018-01-01,2018,3,13.547525,10.198627,6
9,2019-01-01,2019,2,0.000000,0.000000,7
10,2020-01-01,2020,4,0.120000,0.092103,7
11,2021-01-01,2021,6,102.118667,73.979504,9
12,2022-01-01,2022,6,17.500000,13.012572,2
13,2023-01-01,2023,7,3.042059,2.497819,0
14,2024-01-01,2024,2,0.000000,0.000000,0

In [ ]:
analysis.magnitude_growth(ts_df, 2019, 2024)

In [285]:
importlib.reload(analysis_crunchbase);

In [ ]:
aggregated_funding_types_df = analysis_crunchbase.aggregate_by_funding_round_types(selected_funding_df)
analysis_crunchbase.chart_investment_types(aggregated_funding_types_df)

In [ ]:
analysis_crunchbase.chart_deal_sizes(deals_df)

In [303]:
analysis_crunchbase.chart_deal_sizes_counts(deal_counts_df)

alt.Chart(...)

In [320]:
from discovery_utils.utils import charts
importlib.reload(charts);

In [295]:
ts_df.head(5)

,time_period,year,n_rounds,raised_amount_usd_total,raised_amount_gbp_total,n_orgs_founded
0,2010-01-01,2010,5,3.073000,1.929978,5
1,2011-01-01,2011,6,5.775000,3.608702,2
2,2012-01-01,2012,5,1.467900,0.925512,4
3,2013-01-01,2013,2,0.015000,0.009968,10
4,2014-01-01,2014,7,2.890469,1.702734,14

In [327]:
charts.ts_bar_incomplete(
    ts_df,
    variable='raised_amount_gbp_total',
    variable_title='Funding',
    max_complete_year=2022
)

alt.LayerChart(...)

In [330]:
orgs_to_narrow_categories_df = CB.organisation_categories.explode('category_list')

In [332]:
orgs_to_narrow_categories_df.head(5)

                                     id            category_list
0  e1393508-30ea-8a36-3f96-dd3226033abd               Publishing
0  e1393508-30ea-8a36-3f96-dd3226033abd             Social Media
0  e1393508-30ea-8a36-3f96-dd3226033abd  Social Media Management
1  bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7          Cloud Computing
1  bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7            Collaboration

In [333]:
_df = (
    orgs_to_narrow_categories_df
    .merge(CB.group_to_categories, left_on='category_list', right_on='category')
)

In [336]:
CB.group_to_categories

                       group            category
627  Administrative Services   Archiving Service
658  Administrative Services         Call Center
676  Administrative Services   Collection Agency
55   Administrative Services  College Recruiting
592  Administrative Services     Courier Service
..                       ...                 ...
263                    Video       TV Production
18                     Video               Video
300                    Video       Video Editing
161                    Video     Video Streaming
320                    Video     Video on Demand

[1135 rows x 2 columns]

In [335]:
orgs_to_narrow_categories_df.merge()

                                           id            category_list
0        e1393508-30ea-8a36-3f96-dd3226033abd               Publishing
0        e1393508-30ea-8a36-3f96-dd3226033abd             Social Media
0        e1393508-30ea-8a36-3f96-dd3226033abd  Social Media Management
1        bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7          Cloud Computing
1        bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7            Collaboration
...                                       ...                      ...
3682528  054f83d7-d698-4b34-b4ec-293c8648b695               E-Commerce
3682528  054f83d7-d698-4b34-b4ec-293c8648b695              Marketplace
3682529  751cff94-be30-48c8-b2d1-58c8255ece82             Construction
3682530  51f6584f-5289-40fe-8d76-072007eb4c08                      NaN
3682531  3306731f-39c2-43de-9f4d-428a2af9b6cd                      NaN

[11284753 rows x 2 columns]

In [349]:
df = CB.get_companies_in_categories(['Family'])

In [351]:
CB.unique_funding_round_types

['angel',
 'convertible_note',
 'corporate_round',
 'debt_financing',
 'equity_crowdfunding',
 'grant',
 'initial_coin_offering',
 'non_equity_assistance',
 'post_ipo_debt',
 'post_ipo_equity',
 'post_ipo_secondary',
 'pre_seed',
 'private_equity',
 'product_crowdfunding',
 'secondary_market',
 'seed',
 'series_a',
 'series_b',
 'series_c',
 'series_d',
 'series_e',
 'series_f',
 'series_g',
 'series_h',
 'series_i',
 'series_j',
 'series_unknown',
 'undisclosed']

In [352]:
funding_rounds_df = CB.select_funding_rounds(
    org_ids=df.id.to_list(),
    funding_round_types=['angel', 'seed', 'pre_seed', 'series_a']
)

In [356]:
importlib.reload(analysis_crunchbase);

In [358]:
ts_df = analysis_crunchbase.get_timeseries(df, funding_rounds_df, 'year', 2014, 2024)

In [359]:
charts.ts_bar(
    ts_df,
    "raised_amount_gbp_total",
    "Funding",
)

alt.Chart(...)

In [365]:
CB.group_to_categories.category.unique()

array(['Archiving Service', 'Call Center', 'Collection Agency',
       'College Recruiting', 'Courier Service', 'Debt Collections',
       'Delivery', 'Document Preparation', 'Employee Benefits',
       'Extermination Service', 'Facilities Support Services',
       'Housekeeping Service', 'Human Resources', 'Knowledge Management',
       'Office Administration', 'Packaging Services', 'Physical Security',
       'Project Management', 'Staffing Agency', 'Trade Shows',
       'Virtual Workforce', 'Ad Exchange', 'Ad Network', 'Ad Retargeting',
       'Ad Server', 'Ad Targeting', 'Advertising',
       'Advertising Platforms', 'Affiliate Marketing',
       'Local Advertising', 'Mobile Advertising', 'Native Advertising',
       'Outdoor Advertising', 'SEM', 'Social Media Advertising',
       'Video Advertising', 'AgTech', 'Agriculture', 'Animal Feed',
       'Aquaculture', 'Equestrian', 'Farming', 'Forestry', 'Horticulture',
       'Hydroponics', 'Livestock', 'App Discovery', 'Apps',
       'Consumer Applications', 'Enterprise Applications', 'Mobile Apps',
       'Reading Apps', 'Web Apps', 'Artificial Intelligence (AI)',
       'Generative AI', 'Intelligent Systems', 'Machine Learning',
       'Natural Language Processing', 'Predictive Analytics',
       'Robotic Process Automation (RPA)', 'Bioinformatics', 'Biometrics',
       'Biopharma', 'Biotechnology', 'Genetics', 'Life Science',
       'Neuroscience', 'Quantified Self', 'Bitcoin', 'Blockchain',
       'Cryptocurrency', 'Decentralized Finance (DeFi)', 'Ethereum',
       'Non-Fungible Token (NFT)', 'Smart Contracts', 'Web3', 'Apparel',
       'Fashion', 'Laundry and Dry-cleaning', 'Lingerie', 'Shoes',
       'Auctions', 'Classifieds', 'Collectibles', 'Consumer Reviews',
       'Coupons', 'E-Commerce', 'E-Commerce Platforms', 'Flash Sale',
       'Gift', 'Gift Card', 'Gift Exchange', 'Gift Registry',
       'Group Buying', 'Local Shopping', 'Made to Order', 'Marketplace',
       'Office Supplies', 'Online Auctions', 'Personalization',
       'Point of Sale', 'Price Comparison', 'Rental', 'Retail',
       'Retail Technology', 'Secondhand Goods', 'Shopping',
       'Shopping Mall', 'Social Shopping', 'Sporting Goods',
       'Vending and Concessions', 'Virtual Goods', 'Wholesale', 'Adult',
       'Baby', 'Cannabis', 'Children', 'Communities', 'Dating', 'Elderly',
       'Family', 'Funerals', 'Humanitarian', 'LGBT', 'Leisure',
       'Lifestyle', "Men's", 'Online Forums', 'Parenting', 'Pet',
       'Private Social Networking', 'Professional Networking', 'Q&A',
       'Religion', 'Retirement', 'Sex Industry', 'Sex Tech', 'Social',
       'Social Entrepreneurship', 'Teenagers', 'Virtual World', 'Wedding',
       "Women's", 'Young Adults', 'Computer', 'Consumer Electronics',
       'Drones', 'Electronics', 'Google Glass', 'Mobile Devices',
       'Nintendo', 'Playstation', 'Roku', 'Smart Home', 'Wearables',
       'Windows Phone', 'Xbox', 'Beauty', 'Card and Board Games',
       'Cleaning Products', 'Comics', 'Consumer Goods', 'Cosmetics',
       'DIY', 'Eyewear', 'Fast-Moving Consumer Goods', 'Flowers',
       'Furniture', 'Green Consumer Goods', 'Handmade', 'Home Appliances',
       'Jewelry', 'Personal Care and Hygiene', 'Tobacco', 'Toys',
       'Blogging Platforms', 'Books', 'Content Delivery Network',
       'Content Discovery', 'Content Syndication', 'Copywriting',
       'Creative Agency', 'DRM', 'EBooks', 'Journalism', 'News',
       'Photo Editing', 'Photo Sharing', 'Photography', 'Printing',
       'Publishing', 'Social Bookmarking', 'Video Editing',
       'Video Streaming', 'A/B Testing', 'Analytics',
       'Application Performance Management', 'Big Data',
       'Business Intelligence', 'Consumer Research',
       'Data Collection and Labeling', 'Data Governance',
       'Data Integration', 'Data Management', 'Data Mining',
       'Data Visualization', 'Database', 'Facial Recognition',
       'Geospatial', 'Image Recognition', 'Location Based Services',
       'Market Research', 'Product Research', 'Speech Recognition',
       'Test and Measurement', 'Text Analytics', 'Usability Testing',
       'CAD', 'Graphic Design', 'Human Computer Interaction',
       'Industrial Design', 'Interior Design', 'Mechanical Design',
       'Product Design', 'UX Design', 'Web Design', 'Alumni',
       'Charter Schools', 'Continuing Education', 'Corporate Training',
       'E-Learning', 'EdTech', 'Education', 'Edutainment',
       'Higher Education', 'Language Learning', 'MOOC', 'Music Education',
       'Personal Development', 'Primary Education', 'STEM Education',
       'Secondary Education', 'Skill Assessment', 'Special Education',
       'Textbook', 'Training', 'Tutoring', 'Vocational Education',
       'Battery', 'Biofuel', 'Biomass Energy', 'Clean Energy',
       'Electrical Distribution', 'Energy', 'Energy Efficiency',
       'Energy Management', 'Energy Storage', 'Fossil Fuels', 'Fuel',
       'Fuel Cell', 'Geothermal Energy', 'Hydroelectric', 'Oil and Gas',
       'Power Grid', 'Renewable Energy', 'Solar', 'Wind Energy',
       'Concerts', 'Event Management', 'Event Promotion', 'Events',
       'Nightclubs', 'Nightlife', 'Reservations', 'Ticketing',
       'Accounting', 'Angel Investment', 'Asset Management',
       'Auto Insurance', 'Banking', 'Bookkeeping and Payroll',
       'Commercial Insurance', 'Commercial Lending', 'Consumer Lending',
       'Credit', 'Credit Bureau', 'Credit Cards', 'Crowdfunding',
       'Debit Cards', 'FinTech', 'Finance', 'Financial Exchanges',
       'Financial Services', 'Foreign Exchange Trading',
       'Fraud Detection', 'Funding Platform', 'Health Insurance',
       'Hedge Funds', 'Impact Investing', 'Incubators', 'InsurTech',
       'Insurance', 'Leasing', 'Lending', 'Life Insurance',
       'Micro Lending', 'Mobile Payments', 'Payments', 'Personal Finance',
       'Prediction Markets', 'Prepaid Cards', 'Property Insurance',
       'Real Estate Investment', 'Stock Exchanges', 'Tax Consulting',
       'Tax Preparation', 'Trading Platform', 'Transaction Processing',
       'Venture Capital', 'Virtual Currency', 'Wealth Management',
       'Alternative Protein', 'Bakery', 'Brewing', 'Catering', 'Coffee',
       'Confectionery', 'Cooking', 'Craft Beer', 'Dairy',
       'Dietary Supplements', 'Distillery', 'Farmers Market',
       'Food Delivery', 'Food Processing', 'Food Trucks',
       'Food and Beverage', 'Fruit', 'Grocery', 'Herbs and Spices',
       'Meat and Poultry', 'Nutrition', 'Organic Food',
       'Plant-Based Foods', 'Recipes', 'Restaurants', 'Seafood',
       'Snack Food', 'Tea', 'Wine And Spirits', 'Winery', 'Casual Games',
       'Console Games', 'Contests', 'Fantasy Sports', 'Gambling',
       'Gamification', 'Gaming', 'MMO Games', 'Online Games', 'PC Games',
       'Serious Games', 'Video Games', 'CivicTech', 'GovTech',
       'Government', 'Law Enforcement', 'Military', 'National Security',
       'Politics', 'Public Safety', 'Social Assistance', '3D Technology',
       'Application Specific Integrated Circuit (ASIC)',
       'Audio/Visual Equipment', 'Augmented Reality',
       'Cloud Infrastructure', 'Communication Hardware',
       'Communications Infrastructure', 'Computer Vision', 'DSP',
       'Data Center', 'Data Center Automation', 'Data Storage',
       'Drone Management', 'Electronic Design Automation (EDA)',
       'Embedded Systems', 'Field-Programmable Gate Array (FPGA)',
       'Flash Storage', 'GPS', 'GPU', 'Hardware', 'Laser', 'Lighting',
       'NFC', 'Network Hardware', 'Optical Communication',
       'Private Cloud', 'RFID', 'RISC', 'Remote Sensing', 'Robotics',
       'Satellite Communication', 'Semiconductor', 'Sensor',
       'Telecommunications', 'Video Conferencing', 'Virtual Reality',
       'Virtualization', 'Wireless', 'Addiction Treatment',
       'Alternative Medicine', 'Assisted Living', 'Assistive Technology',
       'Child Care', 'Clinical Trials', 'Cosmetic Surgery', 'Dental',
       'Diabetes', 'Elder Care', 'Electronic Health Record (EHR)',
       'Emergency Medicine', 'Fertility', 'First Aid', 'Health Care',
       'Health Diagnostics', 'Home Health Care', 'Hospital', 'Medical',
       'Medical Device', 'Mental Health', 'Nursing and Residential Care',
       'Nutraceutical', 'Oncology', 'Outpatient Care', 'Personal Health',
       'Pharmaceutical', 'Precision Medicine', 'Primary and Urgent Care',
       'Psychology', 'Rehabilitation', 'Telehealth', 'Therapeutics',
       'Veterinary', 'Wellness', 'mHealth',
       'Business Information Systems', 'CMS', 'CRM',
       'Cloud Data Services', 'Cloud Management', 'Cloud Security',
       'Contact Management', 'Cyber Security', 'DevOps',
       'Document Management', 'E-Signature', 'Email', 'IT Infrastructure',
       'IT Management', 'Identity Management', 'Information Services',
       'Information Technology',
       'Information and Communications Technology (ICT)',
       'Intrusion Detection', 'Management Information Systems',
       'Messaging', 'Network Security', 'Penetration Testing',
       'Reputation', 'Sales Automation', 'Scheduling', 'Social CRM',
       'Spam Filtering', 'Technical Support', 'Unified Communications',
       'Video Chat', 'VoIP', 'Cloud Computing', 'Cloud Storage',
       'Darknet', 'Domain Registrar', 'Ediscovery', 'ISP', 'Internet',
       'Internet of Things', 'Music Streaming', 'Online Portals',
       'Product Search', 'SEO', 'SMS', 'Search Engine', 'Semantic Search',
       'Semantic Web', 'Social Media', 'Social Media Management',
       'Social Network', 'Vertical Search', 'Visual Search',
       'Web Browsers', 'Web Hosting', '3D Printing', 'Advanced Materials',
       'Foundries', 'Industrial', 'Industrial Automation',
       'Industrial Engineering', 'Industrial Manufacturing',
       'Machinery Manufacturing', 'Manufacturing', 'Paper Manufacturing',
       'Plastics and Rubber Manufacturing', 'Textiles', 'Wood Processing',
       'Advice', 'Animation', 'Art', 'Audio', 'Audiobooks',
       'Broadcasting', 'Celebrity', 'Content', 'Content Creators',
       'Digital Entertainment', 'Digital Media', 'Film',
       'Film Distribution', 'Film Production', 'Guides',
       'In-Flight Entertainment', 'Independent Music', 'Internet Radio',
       'Media and Entertainment', 'Metaverse', 'Motion Capture', 'Music',
       'Music Label', 'Music Venues', 'Musical Instruments',
       'Performing Arts', 'Podcast', 'Social News', 'TV', 'TV Production',
       'Theatre', 'Video', 'Video on Demand', 'Meeting Software',
       'Wired Telecommunications', 'Android', 'Mobile', 'iOS',
       'Audio Recording and Production', 'Mineral', 'Mining',
       'Mining Technology', 'Natural Resources', 'Precious Metals',
       'Timber', 'Water', 'Indoor Positioning', 'Mapping Services',
       'Navigation', 'Association', 'B2B', 'B2C', 'Charity',
       'Collaboration', 'Collaborative Consumption', 'Commercial',
       'Consumer', 'Crowdsourcing', 'Customer Service', 'Desktop Apps',
       'Emerging Markets', 'Enterprise', 'Franchise', 'Freemium',
       'Generation Y', 'Generation Z', 'Homeless Shelter',
       'Infrastructure', 'Millennials', 'Non Profit', 'Peer to Peer',
       'Product Management', 'Professional Services', 'Real Time',
       'Service Industry', 'Sharing Economy',
       'Small and Medium Businesses', 'Social Impact',
       'Subscription Service', 'Underserved Children', 'Universities',
       'Billing', 'Facebook', 'Google', 'Linux', 'Operating Systems',
       'Tizen', 'Twitter', 'WebOS', 'Windows', 'macOS',
       'Corrections Facilities', 'Homeland Security', 'Privacy',
       'Security', 'Advocacy', 'Business Development', 'Career Planning',
       'Compliance', 'Consulting', 'Employment',
       'Environmental Consulting', 'Field Support', 'Freelance',
       'Innovation Management', 'Intellectual Property', 'Legal',
       'Legal Tech', 'Management Consulting', 'Outsourcing',
       'Quality Assurance', 'Recruiting', 'Risk Management',
       'Social Recruiting', 'Translation Service', 'Architecture',
       'Building Maintenance', 'Building Material',
       'Commercial Real Estate', 'Construction', 'Coworking',
       'Facility Management', 'Green Building',
       'Heating, Ventilation, and Air Conditioning (HVAC)', 'Home Decor',
       'Home Improvement', 'Home Renovation', 'Home Services',
       'Home and Garden', 'Janitorial Service', 'Landscaping', 'Mortgage',
       'PropTech', 'Property Development', 'Property Management',
       'Real Estate', 'Real Estate Brokerage', 'Rental Property',
       'Residential', 'Self-Storage', 'Smart Building', 'Smart Cities',
       'Timeshare', 'Vacation Rental', 'App Marketing', 'Brand Marketing',
       'Cause Marketing', 'Content Marketing', 'Digital Marketing',
       'Digital Signage', 'Direct Marketing', 'Direct Sales',
       'Email Marketing', 'Lead Generation', 'Lead Management', 'Local',
       'Local Business', 'Loyalty Programs', 'Marketing',
       'Marketing Automation', 'Multi-level Marketing',
       'Personal Branding', 'Public Relations', 'Sales',
       'Sales Enablement', 'Social Media Marketing', 'Sponsorship',
       'Aerospace', 'Chemical', 'Chemical Engineering',
       'Civil Engineering', 'Environmental Engineering',
       'Marine Technology', 'Mechanical Engineering', 'Nanotechnology',
       'Nuclear', 'Quantum Computing', 'Software Engineering',
       'Browser Extensions', 'Business Process Automation (BPA)',
       'Chatbot', 'Consumer Software', 'Developer APIs',
       'Developer Platform', 'Developer Tools', 'Embedded Software',
       'Enterprise Resource Planning (ERP)', 'Enterprise Software',
       'File Sharing', 'IaaS', 'Open Source', 'PaaS',
       'Presentation Software', 'Presentations', 'Productivity Tools',
       'QR Codes', 'SNS', 'SaaS', 'Simulation', 'Software',
       'Task Management', 'Virtual Assistant', 'Virtual Desktop',
       'Web Development', 'American Football', 'Baseball', 'Basketball',
       'Boating', 'Cricket', 'Cycling', 'Diving', 'Fitness', 'Golf',
       'Hockey', 'Hunting', 'Motorsports', 'Outdoors', 'Racing',
       'Recreation', 'Rugby', 'Sailing', 'Skiing', 'Soccer', 'Sports',
       'Sports Leagues and Teams', 'Surfing', 'Swimming', 'Table Tennis',
       'Tennis', 'Ultimate Frisbee', 'Volley Ball', 'eSports',
       'Carbon Capture', 'CleanTech', 'GreenTech', 'Organic',
       'Pollution Control', 'Recycling', 'Sustainability',
       'Waste Management', 'Water Purification', 'Wildlife Conservation',
       'Air Transportation', 'Automotive', 'Autonomous Vehicles',
       'Car Sharing', 'Charging Infrastructure', 'Delivery Service',
       'Electric Vehicle', 'Ferry Service', 'Fleet Management',
       'Freight Service', 'Last Mile Transportation', 'Limousine Service',
       'Logistics', 'Marine Transportation', 'Parking',
       'Ports and Harbors', 'Procurement', 'Public Transportation',
       'Railroad', 'Recreational Vehicles', 'Ride Sharing',
       'Same Day Delivery', 'Shipping', 'Shipping Broker', 'Space Travel',
       'Supply Chain Management', 'Taxi Service', 'Transportation',
       'Warehouse Automation', 'Warehousing', 'Water Transportation',
       'Adventure Travel', 'Amusement Park and Arcade', 'Business Travel',
       'Casino', 'Hospitality', 'Hotel', 'Museums and Historical Sites',
       'Parks', 'Resorts', 'Tour Operator', 'Tourism', 'Travel',
       'Travel Accommodations', 'Travel Agency'], dtype=object)

In [383]:
CB.group_vectors

2024-11-20 16:56:59,904 - discovery_utils.getters.crunchbase - INFO - Downloading parquet file: data/crunchbase/Crunchbase_2024-11-18/category_groups.parquet
2024-11-20 16:57:00,025 - discovery_utils.getters.crunchbase - INFO - Successfully downloaded and read parquet file: data/crunchbase/Crunchbase_2024-11-18/category_groups.parquet
2024-11-20 16:57:00,031 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
/Users/karlis.kanders/Code/discovery_utils/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-11-20 16:57:00,892 - sentence_transformers.SentenceTransformer - INFO - Use pytorch device_name: mps
Batches: 100%|██████████| 2/2 [00:00<00:00, 48.85it/s]

,group,vector
0,Administrative Services,"[-0.0789601, -0.057139844, -0.015132315, 0.009..."
1,Advertising,"[-0.06080457, 0.00965797, -0.0334141, 0.022970..."
2,Agriculture and Farming,"[0.011781091, 0.0478218, -0.038464304, 0.02491..."
3,Apps,"[-0.051812097, -0.03198021, 0.0066298256, -0.0..."
4,Artificial Intelligence (AI),"[-0.03369453, 0.0392624, -0.002034516, 0.05440..."
5,Biotechnology,"[-0.05557861, -0.007920985, -0.07175106, -0.06..."
6,Blockchain and Cryptocurrency,"[-0.0159732, 0.06255727, -0.066419, 0.01064516..."
7,Clothing and Apparel,"[-0.02693445, 0.07989401, 0.034079853, 0.05068..."
8,Commerce and Shopping,"[0.012635123, 0.013148435, -0.041306533, 0.012..."
9,Community and Lifestyle,"[0.029243192, 0.008376386, -0.05121899, 0.0815..."
10,Consumer Electronics,"[-0.07881339, 0.02422601, -0.0026573932, -0.05..."
11,Consumer Goods,"[-0.09681703, -0.03564883, -0.019191207, -0.02..."
12,Content and Publishing,"[0.03629123, 0.020708729, -0.06077672, 0.03326..."
13,Data and Analytics,"[-0.0007438743, 0.033310402, -0.073947005, 0.0..."
14,Design,"[-0.05252874, 0.14383362, -0.02038123, -0.0243..."
15,Education,"[0.03087433, 0.09993653, -0.020642994, 0.07698..."
16,Energy,"[-0.035394482, 0.09909571, -0.010701094, 0.142..."
17,Events,"[0.018214291, 0.054726664, 0.033627223, 0.0337..."
18,Financial Services,"[-0.04782137, -0.024695443, -0.07330309, 0.022..."
19,Food and Beverage,"[0.021437543, 0.00943619, 0.0025880905, 0.0597..."
20,Gaming,"[0.039516043, 0.0019357656, 0.0035856124, -0.0..."
21,Government and Military,"[-0.0464795, 0.030652817, 0.022760408, 0.01775..."
22,Hardware,"[-0.043680158, 0.049350902, 0.03700093, -0.040..."
23,Health Care,"[-0.038401213, 0.08679835, 0.026742702, 0.0479..."
24,Information Technology,"[-0.03858126, 0.06103174, -0.023124786, -0.032..."
25,Internet Services,"[-0.07717587, -0.054572243, -0.007423765, -0.1..."
26,Lending and Investments,"[0.052723184, -0.06022945, -0.07201481, -0.004..."
27,Manufacturing,"[-0.050482705, 0.010764777, -0.021324541, 0.00..."
28,Media and Entertainment,"[0.059659917, 0.0055200923, -0.0024522818, -0...."
29,Messaging and Telecommunications,"[-0.02257471, -0.010359122, 0.036388762, -0.04..."
30,Mobile,"[-0.07103204, 0.041052878, 0.025598915, -0.034..."
31,Music and Audio,"[0.078628495, -0.030724509, -0.02527473, -0.05..."
32,Natural Resources,"[-0.005582284, 0.043628264, 0.033273034, 0.034..."
33,Navigation and Mapping,"[0.09844271, -0.025728712, 0.011529489, -0.059..."
34,Other,"[-0.070565484, -0.08505215, -0.06030113, -0.01..."
35,Payments,"[-0.028972393, 0.06844233, -0.011179884, -0.03..."
36,Platforms,"[0.059721928, -0.03505185, -0.019341467, -0.07..."
37,Privacy and Security,"[-0.0750628, 0.09230475, -0.057354014, -0.0211..."
38,Professional Services,"[-0.07836296, 0.0057514873, 0.01432802, -0.021..."
39,Real Estate,"[0.038008813, -0.01965125, -0.031634543, 0.071..."
40,Sales and Marketing,"[-0.03979632, 0.021451753, -0.05784109, -0.028..."
41,Science and Engineering,"[-0.062473327, 0.009831679, 0.022610376, 0.054..."
42,Social Impact,"[0.058845848, 0.057833813, -0.00537645, 0.0457..."
43,Software,"[-0.07127331, 0.022924589, -0.014570662, -0.03..."
44,Sports,"[0.0012440365, 0.07559645, -0.017228417, -0.02..."
45,Sustainability,"[0.0041068844, 0.118057884, 0.006518027, 0.020..."
46,Transportation,"[0.009454301, -0.024513615, 0.017116627, 0.050..."
47,Travel and Tourism,"[0.123107634, 0.01428584, -0.024103565, 0.0555..."
48,Video,"[-0.025287239, -0.029372696, -0.04432926, -0.0..."

In [395]:
CB.find_similar_categories("cyber safety", category_type='narrow')

Batches: 100%|██████████| 1/1 [00:00<00:00, 16.49it/s]

              category  similarity
453     Cyber Security    0.782012
608           Security    0.583227
467   Network Security    0.557836
16   Physical Security    0.529581
370      Public Safety    0.522218
607            Privacy    0.467996
451     Cloud Security    0.454629
484           Internet    0.449748
368  National Security    0.436531
474  Technical Support    0.415475

In [368]:
unique_groups = CB.group_to_categories.group.unique()
vectors = CB.embedding_model.encode(unique_groups)

Batches: 100%|██████████| 2/2 [00:00<00:00,  5.92it/s]

In [371]:
len(unique_groups)

49

In [377]:
len(list(vectors))

49

In [379]:
import pandas as pd
vectors_df = pd.DataFrame(
    data={"group": unique_groups, "vector": list(vectors)}
)

In [380]:
query_embedding = CB.embedding_model.encode(["Cybersecurity"])[0]

Batches: 100%|██████████| 1/1 [00:00<00:00,  2.34it/s]

In [381]:
import numpy as np
(
    vectors_df            
    .assign(similarity = vectors_df.vector.apply(lambda x: np.dot(query_embedding, x)))
    .sort_values("similarity", ascending=False)
    .drop(columns="vector")
    .head(10)
)

                           group  similarity
37          Privacy and Security    0.508416
24        Information Technology    0.434857
25             Internet Services    0.424183
43                      Software    0.387372
4   Artificial Intelligence (AI)    0.377659
0        Administrative Services    0.373829
5                  Biotechnology    0.357013
41       Science and Engineering    0.336290
22                      Hardware    0.316858
13            Data and Analytics    0.311445

In [396]:
orgs_cyber_df = CB.get_companies_in_categories(["Cyber Security"])

In [400]:
orgs_parenting_df = CB.get_companies_in_categories(["Family", "Parenting", "Children", "Teenagers", "Child Care"])

In [401]:
matching_ids = set(orgs_cyber_df.id.to_list()).intersection(orgs_parenting_df.id.to_list())

In [402]:
len(matching_ids)

12

In [420]:
importlib.reload(charts)

In [404]:
# CB.organisations_enriched.query("id in @matching_ids")

In [417]:
ts_test = pd.concat([
    ts_df.assign(category="Cyber Security"),
    ts_df.assign(category="Parenting").assign(raised_amount_gbp_total=lambda df: df.raised_amount_gbp_total * 0.5)
], ignore_index=True)

In [428]:
(
    charts.configure_plots(
        charts.ts_bar_incomplete(
        ts_test,
        "raised_amount_gbp_total",
        "Funding",
        categories_to_show=["Cyber Security", "Parenting"],
        category_column="category",
        max_complete_year=2022
    ), "Ahahaha")
)

alt.LayerChart(...)